name: List services in GCP

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Adicionando esse passo

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: google-github-actions/auth@v2
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/631636540775/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'terraform-github@unique-nebula-452817-i5.iam.gserviceaccount.com'
          audience: 'https://github.com/johnny-paixao/terraform-datasets-bq'

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
