name: List services in GCP and Deploy Terraform using Cloud Build

on:
  push:
    branches:
      - main


permissions:
  id-token: write  # Necessário para autenticação OIDC

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/631636540775/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'cloudbuild-sa@unique-nebula-452817-i5.iam.gserviceaccount.com'
        audience: 'https://github.com/johnny-paixao/terraform-datasets-bq'

    - name: Run Terraform via Cloud Build
      run: |
        gcloud builds submit \
          --project="${{ secrets.PROJECT_ID }}" \
          --region="${{ secrets.LOCATION }}" \
          --config="cloudbuild.yaml" \
          --substitutions=_PROJECT_ID="${{ secrets.PROJECT_ID }}",_TF_STATE_BUCKET="${{ secrets.TF_STATE_BUCKET }}",_TF_STATE_PREFIX="${{ secrets.TF_STATE_PREFIX }}",_GOOGLE_PROVIDER_VERSION="${{ secrets.GOOGLE_PROVIDER_VERSION }}" \
          --verbosity="debug"
